apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
spec:
  template:
    spec:
      serviceAccount: {{ .Values.name }}
      containers:
      - name: test
        image: {{ .Values.image }}
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
      restartPolicy: Never
  backoffLimit: 0