apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cockroachclients.ponglehub.co.uk
spec:
  group: ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deployment:
                  type: string
                database:
                  type: string
                username:
                  type: string
                secret:
                  type: string
              required: [ deployment, database, username, secret ]
            status:
              type: object
              properties:
                ready:
                  type: boolean
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Ready
        type: boolean
        description: Defines whether the client secret has been created
        jsonPath: .status.ready
  scope: Namespaced
  names:
    plural: cockroachclients
    singular: cockroachclient
    kind: CockroachClient
    shortNames:
    - cc
    - ccs