apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: natsclusters.ponglehub.co.uk
spec:
  group: ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                ready:
                  type: boolean
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Ready
        type: boolean
        description: Defines whether the database is running
        jsonPath: .status.ready
  scope: Namespaced
  names:
    plural: natsclusters
    singular: natscluster
    kind: NatsCluster
    shortNames:
    - nc
    - ncs