apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: natsclients.ponglehub.co.uk
spec:
  group: ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dbRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required: [ name, namespace ]
                secret:
                  type: string
              required: [ dbRef, secret ]
            status:
              type: object
              properties:
                ready:
                  type: boolean
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Ready
        type: boolean
        description: Defines whether the client secret has been created
        jsonPath: .status.ready
  scope: Namespaced
  names:
    plural: natsclients
    singular: natsclient
    kind: NatsClient
    shortNames:
    - nc
    - ncs