apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresclients.ponglehub.co.uk
spec:
  group: ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cluster:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required: [ name, namespace ]
                database:
                  type: string
                owner:
                  type: boolean
                username:
                  type: string
                secret:
                  type: string
              required: [ cluster, database, username, secret ]
            status:
              type: object
              properties:
                ready:
                  type: boolean
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Ready
        type: boolean
        description: Defines whether the client secret has been created
        jsonPath: .status.ready
  scope: Namespaced
  names:
    plural: postgresclients
    singular: postgresclient
    kind: PostgresClient
    shortNames:
    - pgcl
    - pgcls