apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisclients.ponglehub.co.uk
spec:
  group: ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deployment:
                  type: string
                unit:
                  type: integer
                secret:
                  type: string
              required: [ deployment, unit, secret ]
            status:
              type: object
              properties:
                ready:
                  type: boolean
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Ready
        type: boolean
        description: Defines whether the client secret has been created
        jsonPath: .status.ready
  scope: Namespaced
  names:
    plural: redisclients
    singular: redisclient
    kind: RedisClient
    shortNames:
    - rc
    - rcs