# image:

name: db-operator
replicas: 1

rbacs:
- apiGroups: ["apps", ""]
  resources: ["statefulsets", "services", "secrets", "events", "deployments"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: ["ponglehub.co.uk"]
  resources: ["postgresclusters", "postgresclusters/status", "postgresmigrations", "postgresclients", "postgresclients/status", "redisclusters", "redisclients", "natsclusters", "natsclients"]
  verbs: ["get", "list", "watch", "update"]