# image:

name: db-operator
replicas: 1

rbacs:
- apiGroups: ["apps", ""]
  resources: ["statefulsets", "services", "secrets", "events", "deployments"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: ["ponglehub.co.uk"]
  resources: ["postgresclusters", "postgresclusters/status", "postgresclients", "postgresclients/status"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["ponglehub.co.uk"]
  resources: ["redisclusters", "redisclusters/status", "redisclients", "redisclients/status"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["ponglehub.co.uk"]
  resources: ["natsclusters", "natsclusters/status", "natsclients", "natsclients/status"]
  verbs: ["get", "list", "watch", "update"]