apiVersion: db-operator.benjamin-wright.github.com/v1alpha1
kind: PostgresDatabase
metadata:
  name: example-db
  namespace: default
spec:
  databaseName: my-db
  postgresVersion: "17"
  storageSize: 1Gi
---
apiVersion: db-operator.benjamin-wright.github.com/v1alpha1
kind: RedisDatabase
metadata:
  name: example-redis
  namespace: default
spec:
  storageSize: 500Mi
