apiVersion: db-operator.benjamin-wright.github.com/v1alpha1
kind: PostgresDatabase
metadata:
  name: my-postgres-database
  labels:
    db-operator.benjamin-wright.github.com/operator-instance: test
spec:
  databaseName: mydatabase
  postgresVersion: "17"
  storageSize: "1Gi"