apiVersion: v2
name: db-operator-chart
description: Kubernetes operator for managing PostgresDatabase and PostgresCredential custom resources
type: application
version: 1.1.4
appVersion: "1.1.4"
keywords:
  - operator
  - postgres
  - database
maintainers:
  - name: games-hub
