image:
  repository: localhost:5001/db-operator
  tag: latest
  pullPolicy: IfNotPresent

migrationImage:
  repository: localhost:5001/db-migrations
  tag: latest
  pullPolicy: IfNotPresent

serviceAccountName: ""

instanceName: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

