{{- if .Values.mcp.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "db-operator.mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "db-operator.mcp.labels" . | nindent 4 }}
{{- end }}
