# image:
name: db-operator-test

rbacs:
- apiGroups: ["apps", ""]
  resources: ["statefulsets", "services", "secrets", "events"]
  verbs: ["create", "get", "list", "watch", "update", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: ["ponglehub.co.uk"]
  resources: ["cockroachdbs", "cockroachmigrations", "cockroachclients", "redisdbs", "redisclients"]
  verbs: ["get", "create", "list", "watch", "update", "deletecollection"]