name: Chart Publish
run-name: ${{ github.actor }} is publishing a new chart version
on:
  push:
    tags:
      - '*'
jobs:
  chart:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Install Helm
        uses: azure/setup-helm@v3
      - uses: actions/checkout@v3
      - name: build
        run: helm package deploy/chart --version ${{ github.ref_name }} --app-version ${{ github.ref_name }}
      - name: push to dockerhub
        run: helm push operator-${{ github.ref_name }}.tgz oci://registry-1.docker.io/benwright
