name: Publishing a new version
run-name: ${{ github.actor }} is publishing a new version
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v -o ./dist/app ./cmd/operator/main.go
      - name: Image
        uses: docker/build-push-action@v4
        with:
          context: ./dist
          file: ./deploy/Dockerfile
          push: true
          tags: benwright/db-operator:${{ github.ref_name }}