name: Tag Publish
run-name: ${{ github.actor }} is publishing a new tag version
on:
  push:
    tags:
      - '*'
jobs:
  go-images:
    strategy:
      matrix:
        include:
        - app: db-migrations
          dockerfile: migrations.Dockerfile
        - app: db-operator
          dockerfile: operator.Dockerfile
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build & Push
        run: docker buildx build --push --platform linux/amd64,linux/arm64 --progress plain -t docker.io/benwright/${{ matrix.app }}:${{ github.ref_name }} -f ${{ matrix.dockerfile }} .
